<?php

/**
 * Details_commandesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Details_commandesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Details_commandesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Details_commandes');
    }
}