<?php

/**
 * CommandesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EditionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EditionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Edition');
    }
}