<?php

/**
 * LivresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LivresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LivresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Livres');
    }
}