<?php

/**
 * MembresTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembresTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembresTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Membres');
    }
}